### ISSUE TITLE
decrypt use ECB mode, when the input less than 16 chars, decrypt error

### ISSUE THREAD

**Issue by nb7123** [kokke/tiny-AES128-C#33]
'BlockCopy' just copy 'KEYLEN' chars

**Comment by kokke** [comment]
This is by design. You need to pass the AES library valid inputs. 
That means making sure you're using correctly sized buffers and correctly zero-pad them as well, if needed.

As the readme says: "There is no built-in error checking or protection from out-of-bounds memory access errors as a result of malicious input.". 
The algorithm expects blocks with lengths divisible by 16 bytes. 
If you want to encrypt less data than a full block, pad it or use a stream oriented cipher mode like OFB :)
