### ISSUE TITLE
null pointer is used

### ISSUE THREAD

**Issue by nizqsut** [kokke/tiny-AES128-C#35]
Hi, kokke.

I forked your code and used in my project. 
I met a problem. Let me show you code.

In this functon:
void AES128_CBC_encrypt_buffer(
        uint8_t* output, uint8_t* input,
        uint32_t length, const uint8_t* key, const uint8_t* iv)
If I pass parameter "iv" and "iv" equals 0, then:
  if(iv != 0)  //cause iv equals 0, then static var Iv isn't assimented, Iv's default value maybe 0
  {
    Iv = (uint8_t*)iv; 
  }

and then:
static void XorWithIv(uint8_t* buf)
{
  uint8_t i;
  for(i = 0; i < KEYLEN; ++i)
  {
    //casue Iv isn't initialized, this line probably generates segmentfalut
    buf[i] ^= Iv[i]; 
  }
}

**Comment by kokke** [comment]
The README clearly states that no error checking is performed, and that if you wish to protect for malicious input, you should build it ontop of the library yourself :)

> There is no built-in error checking or protection from out-of-bounds memory access errors as a result of malicious input.

This disclaimer may seem nonchalant, but the reason is that I - and many of the other users - use this code in embedded systems, where it can often be guaranteed that no malicious inputs will be given, and that the sizes of the buffers are always multiples of 16 etc.

You can use static analysis tools and model checkers (CBMC is my favorite) to verify these assertions in critical code.
