### ISSUE TITLE
memcpy rather than loop?

### ISSUE THREAD

**Issue by redorkulated** [kokke/tiny-AES128-C#39]
Hey,

Great bit of code, should save me from using openssl (hopefully)! Just curious, on this section what made you use a loop rather than just memcpy(output,input,KEYLEN)  ?:

`
static void BlockCopy(uint8_t* output, uint8_t* input)
{
  uint8_t i;
  for (i=0;i<KEYLEN;++i)
  {
    output[i] = input[i];
  }
}
`

Of course memcpy itself is a call and then another loop but it might on some computers/compilers it might be more optimised then byte by byte copying

**Comment by kokke** [comment]
Hi Michael,

Your guess is correct, it is to save a function call and spare the dependency on memcpy.
The reason is also that it produces the smallest code output using the compilers I've benchmarked. It is a valid candidate for optimization if you are already linking memcpy into the C runtime, sure :)

**Comment by redorkulated** [comment]
Very interesting :D , I do love it how you can start to refine C down so much to save on ASM instructions! I have never had to work in an embedded environment but I still love to worry about each byte and instruction being pointlessly wasted.

**Comment by kokke** [comment]
The project started out because I needed the algorithm but didn't have enough space for what I could download on the web :)

There are smaller implementations, which I haven't had the time to review.
Links in this issue:
https://github.com/kokke/tiny-AES128-C/issues/17
