### ISSUE TITLE
aes128-cbc encrypt result differ from openssl command line?

### ISSUE THREAD

**Issue by daiziyi** [kokke/tiny-AES128-C#44]
hi.  I am a beginner of encrypt algorithm.
i want to compare the 'tiny-aes128-c' encrypt with openssl. but the encrypt  results are different. 

Here is my practice: 
### the tiny-AES128-C code: 
```
#include "aes.h"
#include <stdio.h>

void phex(uint8_t *str, int len)
{
    int i;
    for(i=0; i<len; ++i){
        printf("%.2x ", str[i]);
    }
    printf("\n");
}

int main()
{
    const uint8_t key[16] = {0x12, 0x23};
    const uint8_t iv[16] =  {0xF1, 0x23};
    uint8_t in[16] = "1234567890abc";
    uint8_t out[16];

    AES128_CBC_encrypt_buffer(out, in, sizeof(in), key, iv);
    phex(out, sizeof(out));

    return 0;
}
```
the tiny-AES128-C encrypt result is: 
```
fd a3 86 e1 51 3f 9f 4a 8b 21 84 ee b4 bd 79 3e 
```

### openssl commnad line encrypt
```
$echo "1234567890abc" > plain.txt
$openssl enc -aes-128-cbc -in plain.txt  -out encrypt.txt  -K 1223 -iv f123 -p
$xxd encrypt.txt

```
![default](https://cloud.githubusercontent.com/assets/5773786/21257694/76541df8-c3b4-11e6-8eda-55948ae6e8aa.png)
$xxd plain.txt
![default](https://cloud.githubusercontent.com/assets/5773786/21257799/e3ace79a-c3b4-11e6-9562-59ce88332012.png)

$xxd encrypt.txt
![default](https://cloud.githubusercontent.com/assets/5773786/21257713/94b45c68-c3b4-11e6-9883-906cdbc7f503.png)

## **Result Compare**
tiny-aes128-c:
```
fd a3 86 e1 51 3f 9f 4a 8b 21 84 ee b4 bd 79 3e
````
openssl:
```
c5 af 18 cb dd ee 99 23 03 74 6a 21 9b b6 3f 99
```
why is difference? 

Thank you!

**Comment by namreeb** [comment]
Is the OpenSSL version including a null terminator?

**Comment by ardiri** [comment]
OPENSSL uses PKCS7 padding.

PKCS7 padding does not pad with zeros; instead, it pads with the remainder. so, if there are 4 bytes missing to make it modulus 16; the input will be padded with 4 bytes containing the number 4. PKCS7 also requires at least ONE padding byte; so if your input length is exactly modulus 16 - you need to add 16 bytes, containing the value 16.

i implemented AES-128/192/256 working against openSSL (within PHP) initially based on the code in this repository; but in order to support 192/256 i had to make some minor changes in addition to dealing with PKCS7 padding.

http://ardiri.com/blog/utls_defining_lightweight_security_for_iot_part_5

**Comment by wvengen** [comment]
The fork by [triangulum-com-au](https://github.com/triangulum-com-au/tiny-AES128-C) supports pkcs7 padding (I've used it with success).

**Comment by daiziyi** [comment]
Thanks to @namreeb @ardiri @wvengen helps , I did not consider the padding at the first time and the program appears different result.  Thank you!
